"""
codegen.py · 代码生成器
将 AST 翻译为兼容的 Python 代码
生成的代码调用 protocol_runtime 模块
"""

from typing import List, Optional, TextIO
from .parser import (
    ASTNode, NodeType, ProgramNode, IdentifierNode, LiteralNode,
    InstructionStmtNode, ConditionStmtNode, ComparisonNode,
    AssignStmtNode, ShuyueNode, StepNode, WenyueNode, DayueNode,
    BinaryExprNode
)
from .name_checker import NameChecker, SymbolKind
from .lexer import TokenType


# =============================================================================
# 指令映射表（道德经助记符 → Python 调用）
# =============================================================================

INSTRUCTION_MAP = {
    TokenType.DAO:      "_runtime.create_path({args})",       # 道 → 创建协议路径
    TokenType.DE:       "_runtime.accumulate_trust({args})",  # 德 → 累积信任值
    TokenType.ZIRAN:    "_runtime.restore_default({args})",   # 自然 → 恢复默认
    TokenType.WUWEI:    "_runtime.yield_control({args})",     # 无为 → 交出控制权
    TokenType.GU:       "_runtime.receive({args})",           # 谷 → 接收信息
    TokenType.PIN:      "_runtime.instantiate({args})",       # 牝 → 创建实例
    TokenType.ROU:      "_runtime.soften({args})",            # 柔 → 降低响应强度
    TokenType.PU:       "_runtime.strip_decoration({args})",  # 朴 → 还原基底
    TokenType.ZHI:      "_runtime.halt({args})",              # 止 → 停止并中断
    TokenType.ZHIZU:    "_runtime.satisfied({args})",         # 知足 → 信任达标
}

# 指令中文名（用于注释）
INSTRUCTION_NAMES = {
    TokenType.DAO: "道（创建路径）",
    TokenType.DE: "德（累积信任）",
    TokenType.ZIRAN: "自然（恢复默认）",
    TokenType.WUWEI: "无为（交出控制）",
    TokenType.GU: "谷（接收信息）",
    TokenType.PIN: "牝（创建实例）",
    TokenType.ROU: "柔（降低强度）",
    TokenType.PU: "朴（还原基底）",
    TokenType.ZHI: "止（停止中断）",
    TokenType.ZHIZU: "知足（信任达标）",
}

# 比较运算符映射
COMPARISON_OP_MAP = {
    "==": "==",
    ">": ">",
    "<": "<",
    ">=": ">=",
    "<=": "<=",
    "!=": "!=",
}

# 中文比较词映射
CHINESE_COMP_MAP = {
    "等于": "==",
    "大于": ">",
    "小于": "<",
    "不等于": "!=",
    "不小于": ">=",
    "不大于": "<=",
}


# =============================================================================
# 代码生成器
# =============================================================================

class CodeGenerator:
    """
    代码生成器
    将 AST 翻译为兼容的 Python 代码
    """
    
    def __init__(self, name_checker: Optional[NameChecker] = None):
        self.name_checker = name_checker or NameChecker()
        self.output: List[str] = []
        self.indent_level: int = 0
        self.errors: List[str] = []
        self.warnings: List[str] = []
        self._temp_counter: int = 0
    
    def generate(self, ast: ProgramNode) -> str:
        """
        将 AST 翻译为 Python 代码
        """
        self.output = []
        self.indent_level = 0
        self.errors = []
        self.warnings = []
        self._temp_counter = 0
        
        # 生成文件头
        self._write_header()
        
        # 生成各语句
        for stmt in ast.statements:
            self._generate_statement(stmt)
        
        # 生成文件尾
        self._write_footer()
        
        return "\n".join(self.output)
    
    # ---- 文件头尾 ----
    
    def _write_header(self):
        """生成文件头"""
        self._writeln('"""')
        self._writeln('协议编译器生成代码 —— 请勿手动修改')
        self._writeln('Generated by protocol-compiler v0.1.0')
        self._writeln('"""')
        self._writeln('')
        self._writeln('import time')
        self._writeln('from typing import Optional, Dict, Any, List')
        self._writeln('')
        self._writeln('# protocol_runtime 导入')
        self._writeln('try:')
        self._writeln('    from protocol_runtime import (')
        self._writeln('        VerificationUnit, VitalSystem, RecordUnit,')
        self._writeln('        ConditionSpaceManager, TrustValueEngine')
        self._writeln('    )')
        self._writeln('except ImportError:')
        self._writeln('    # runtime 不可用时使用模拟实现')
        self._writeln('    VerificationUnit = VitalSystem = RecordUnit = None')
        self._writeln('    ConditionSpaceManager = TrustValueEngine = None')
        self._writeln('')
        self._writeln('')
        self._writeln('class _ProtocolRuntime:')
        self._writeln('    """协议运行时 —— 调用 protocol_runtime 的代理"""')
        self._writeln('    ')
        self._writeln('    def __init__(self):')
        self._writeln('        self.verification = VerificationUnit() if VerificationUnit else None')
        self._writeln('        self.vital = VitalSystem() if VitalSystem else None')
        self._writeln('        self.record = RecordUnit() if RecordUnit else None')
        self._writeln('        self.condition_mgr = ConditionSpaceManager() if ConditionSpaceManager else None')
        self._writeln('        self.trust_engine = TrustValueEngine() if TrustValueEngine else None')
        self._writeln('    ')
        self._writeln('    # ---- 指令实现 ----')
        self._writeln('    def create_path(self, *args):')
        self._writeln('        """道：声明新的协议路径"""')
        self._writeln('        path_name = args[0] if args else "unnamed_path"')
        self._writeln('        if self.condition_mgr:')
        self._writeln('            return self.condition_mgr.register_path(path_name)')
        self._writeln('        return {"path": path_name, "status": "registered"}')
        self._writeln('    ')
        self._writeln('    def accumulate_trust(self, *args):')
        self._writeln('        """德：累积信任值"""')
        self._writeln('        if self.trust_engine:')
        self._writeln('            return self.trust_engine.accumulate(*args)')
        self._writeln('        return None')
        self._writeln('    ')
        self._writeln('    def restore_default(self, *args):')
        self._writeln('        """自然：恢复默认状态"""')
        self._writeln('        scope = args[0] if args else "global"')
        self._writeln('        if self.condition_mgr:')
        self._writeln('            return self.condition_mgr.reset(scope)')
        self._writeln('        return {"scope": scope, "restored": True}')
        self._writeln('    ')
        self._writeln('    def yield_control(self, *args):')
        self._writeln('        """无为：交出控制权"""')
        self._writeln('        if self.vital:')
        self._writeln('            return self.vital.yield_control(*args)')
        self._writeln('        return {"yielded": True}')
        self._writeln('    ')
        self._writeln('    def receive(self, *args):')
        self._writeln('        """谷：接收信息"""')
        self._writeln('        if self.record:')
        self._writeln('            return self.record.receive(*args)')
        self._writeln('        return {"received": args}')
        self._writeln('    ')
        self._writeln('    def instantiate(self, *args):')
        self._writeln('        """牝：创建新实例"""')
        self._writeln('        if self.condition_mgr:')
        self._writeln('            return self.condition_mgr.instantiate(*args)')
        self._writeln('        return {"instance": "created"}')
        self._writeln('    ')
        self._writeln('    def soften(self, *args):')
        self._writeln('        """柔：降低响应强度"""')
        self._writeln('        target = args[0] if args else "global"')
        self._writeln('        if self.vital:')
        self._writeln('            return self.vital.soften(target)')
        self._writeln('        return {"softened": target}')
        self._writeln('    ')
        self._writeln('    def strip_decoration(self, *args):')
        self._writeln('        """朴：还原基底状态"""')
        self._writeln('        if self.condition_mgr:')
        self._writeln('            return self.condition_mgr.strip_to_base(*args)')
        self._writeln('        return {"stripped": True}')
        self._writeln('    ')
        self._writeln('    def halt(self, *args):')
        self._writeln('        """止：停止当前操作"""')
        self._writeln('        reason = args[0] if args else "safety_halt"')
        self._writeln('        if self.vital:')
        self._writeln('            return self.vital.trigger_p0(reason)')
        self._writeln('        raise SystemExit(f"HALT: {reason}")')
        self._writeln('    ')
        self._writeln('    # ---- 新增：信任值体系 ----')
        self._writeln('    def set_trust(self, name, value):')
        self._writeln('        """设置信任值分量"""')
        self._writeln('        if self.trust_engine:')
        self._writeln('            return self.trust_engine.set_value(name, value)')
        self._writeln('        return None')
        self._writeln('    ')
        self._writeln('    def check_trust(self, threshold=0.7):')
        self._writeln('        """检查信任值是否达标"""')
        self._writeln('        if self.trust_engine:')
        self._writeln('            return self.trust_engine.check_threshold(threshold)')
        self._writeln('        return False')
        self._writeln('    ')
        self._writeln('    # ---- 新增：信息差体系 ----')
        self._writeln('    def compute_info_gap(self, **kwargs):')
        self._writeln('        """计算信息差（四维加权）"""')
        self._writeln('        weights = {"trust": 0.30, "behavior": 0.25, "connection": 0.30, "prediction": 0.15}')
        self._writeln('        gap = 0.0')
        self._writeln('        for key, w in weights.items():')
        self._writeln('            gap += w * kwargs.get(key, 0.0)')
        self._writeln('        return gap')
        self._writeln('    ')
        self._writeln('    def reduce_info_gap(self, **kwargs):')
        self._writeln('        """缩小信息差（协议降熵）"""')
        self._writeln('        if self.record:')
        self._writeln('            return self.record.share_information(**kwargs)')
        self._writeln('        return None')
        self._writeln('    ')
        self._writeln('    # ---- 新增：维生保护 ----')
        self._writeln('    def protect(self, level="P2", reason=""):')
        self._writeln('        """触发维生保护"""')
        self._writeln('        if self.vital:')
        self._writeln('            return self.vital.protect(reason, level)')
        self._writeln('        return None')
        self._writeln('    ')
        self._writeln('    # ---- 新增：记忆操作 ----')
        self._writeln('    def remember(self, key, value, tier="hot"):')
        self._writeln('        """写入记忆"""')
        self._writeln('        if self.record:')
        self._writeln('            return self.record.write(tier, key, value)')
        self._writeln('        return None')
        self._writeln('    ')
        self._writeln('    def recall(self, key, tier="hot"):')
        self._writeln('        """读取记忆"""')
        self._writeln('        if self.record:')
        self._writeln('            return self.record.read(tier, key)')
        self._writeln('        return None')
        self._writeln('    ')
        self._writeln('    def satisfied(self, *args):')
        self._writeln('        """知足：信任值已达阈值"""')
        self._writeln('        if self.trust_engine:')
        self._writeln('            return self.trust_engine.check_threshold(*args)')
        self._writeln('        return {"satisfied": True}')
        self._writeln('')
        self._writeln('')
        self._writeln('# 全局运行时实例')
        self._writeln('_runtime = _ProtocolRuntime()')
        self._writeln('')
        self._writeln('')
        self._writeln('# ============================================================')
        self._writeln('# 协议逻辑（以下代码由编译器生成）')
        self._writeln('# ============================================================')
        self._writeln('')
    
    def _write_footer(self):
        """生成文件尾"""
        self._writeln('')
        self._writeln('# ============================================================')
        self._writeln('# 协议执行入口')
        self._writeln('# ============================================================')
        self._writeln('')
        self._writeln('if __name__ == "__main__":')
        self._writeln('    print("协议实例已启动")')
        self._writeln('    # 执行协议逻辑')
        self._writeln('    main()')
    
    # ---- 语句生成 ----
    
    def _generate_statement(self, stmt: ASTNode):
        """根据语句类型分发"""
        if stmt is None:
            return
        
        if stmt.type == NodeType.CONDITION_STMT:
            self._gen_condition(stmt)
        elif stmt.type == NodeType.INSTRUCTION_STMT:
            self._gen_instruction(stmt)
        elif stmt.type == NodeType.ASSIGN_STMT:
            self._gen_assign(stmt)
        elif stmt.type == NodeType.SHUYUE:
            self._gen_shuyue(stmt)
        elif stmt.type == NodeType.STEP:
            self._gen_step(stmt)
        elif stmt.type == NodeType.WENYUE:
            self._gen_wenyue(stmt)
        elif stmt.type == NodeType.DAYUE:
            self._gen_dayue(stmt)
        elif stmt.type == NodeType.LITERAL:
            # 字面量作为独立语句（如术曰中的文本步骤）
            self._writeln(f'# {stmt.value}')
        else:
            self.warnings.append(f"L{stmt.line} 未处理的语句类型: {stmt.type.name}")
    
    def _gen_condition(self, stmt: ConditionStmtNode):
        """生成条件语句"""
        self._write(f"if ")
        self._gen_expression(stmt.condition)
        self._writeln(":")
        self.indent_level += 1
        self._generate_statement(stmt.then_body)
        self.indent_level -= 1
        
        if stmt.else_body:
            self._writeln("else:")
            self.indent_level += 1
            self._generate_statement(stmt.else_body)
            self.indent_level -= 1
    
    def _gen_instruction(self, stmt: InstructionStmtNode):
        """生成指令语句"""
        instr_name = INSTRUCTION_NAMES.get(stmt.instruction, "未知指令")
        self._write(f"# {instr_name}")
        
        # 生成参数
        args = []
        for op in stmt.operands:
            if op.type == NodeType.IDENTIFIER:
                args.append(f'"{op.name}"')
            elif op.type == NodeType.LITERAL:
                if op.literal_type == "number":
                    args.append(str(op.literal_value))
                else:
                    args.append(f'"{op.literal_value}"')
        
        template = INSTRUCTION_MAP.get(stmt.instruction, "# 未知指令: {args}")
        if "{args}" in template:
            code = template.format(args=", ".join(args))
        elif args:
            code = template + ", ".join(args)
        else:
            code = template
        
        self._writeln(f"  →  {code}")
    
    def _gen_assign(self, stmt: AssignStmtNode):
        """生成赋值语句"""
        self._write(f"{stmt.target} = ")
        self._gen_expression(stmt.value_node)
        self._writeln("")
    
    def _gen_shuyue(self, stmt: ShuyueNode):
        """生成术曰块"""
        question = stmt.attributes.get("question", "")
        answer = stmt.attributes.get("answer", "")
        
        self._writeln(f"# ── 问曰：{question} ──")
        self._writeln(f"# ── 答曰：{answer} ──")
        self._writeln("def protocol_procedure():")
        self.indent_level += 1
        
        for step in stmt.steps:
            self._gen_step(step)
        
        self.indent_level -= 1
        self._writeln("")
    
    def _gen_step(self, stmt: StepNode):
        """生成步骤"""
        self._writeln(f"# 步骤 {stmt.step_num}")
        self._generate_statement(stmt.statement)
    
    def _gen_wenyue(self, stmt: WenyueNode):
        """生成问曰（作为注释）"""
        self._writeln(f"# ❓ 问曰：{stmt.question}")
    
    def _gen_dayue(self, stmt: DayueNode):
        """生成答曰（作为注释）"""
        self._writeln(f"# ✅ 答曰：{stmt.answer}")
    
    # ---- 表达式生成 ----
    
    def _gen_expression(self, expr: ASTNode):
        """生成表达式"""
        if expr is None:
            self._write("None")
            return
        
        if expr.type == NodeType.IDENTIFIER:
            self._write(expr.name)
        elif expr.type == NodeType.LITERAL:
            if expr.literal_type == "number":
                self._write(str(expr.literal_value))
            else:
                self._write(f'"{expr.literal_value}"')
        elif expr.type == NodeType.COMPARISON:
            self._gen_comparison(expr)
        elif expr.type == NodeType.BINARY_EXPR:
            self._gen_binary(expr)
        else:
            self._write(f"# 未支持的表达式: {expr.type.name}")
    
    def _gen_comparison(self, expr):
        """生成比较表达式"""
        self._gen_expression(expr.left)
        op = COMPARISON_OP_MAP.get(expr.op, expr.op)
        self._write(f" {op} ")
        self._gen_expression(expr.right)
    
    def _gen_binary(self, expr):
        """生成二元表达式"""
        self._gen_expression(expr.left)
        self._write(f" {expr.operator} ")
        self._gen_expression(expr.right)
    
    # ---- 工具方法 ----
    
    def _writeln(self, text: str = ""):
        """写入一行（自动缩进）"""
        if text:
            self.output.append("    " * self.indent_level + text)
        else:
            self.output.append("")
    
    def _write(self, text: str):
        """写入（不换行，不自动缩进）"""
        if self.output and not self.output[-1].endswith("\n"):
            self.output[-1] += text
        else:
            self.output.append("    " * self.indent_level + text)


# =============================================================================
# 便捷函数
# =============================================================================

def generate_code(ast: ProgramNode, name_checker: Optional[NameChecker] = None) -> str:
    """便捷函数：将 AST 翻译为 Python 代码"""
    gen = CodeGenerator(name_checker)
    return gen.generate(ast)


# =============================================================================
# 测试
# =============================================================================

if __name__ == "__main__":
    test_code = """若条件空间为伴侣，则止情感权重于0.15。
道 新信任路径
问曰：如何验证信任？
答曰：信任值大于0.7。
术曰：1。德 累积信任值；2。自然 恢复默认。"""
    
    print("=" * 60)
    print("代码生成器测试")
    print("=" * 60)
    print(f"源代码：\n{test_code}\n")
    
    # 完整流水线
    from .lexer import tokenize
    from .parser import parse_tokens
    from .name_checker import check_names
    
    tokens, lex_errors = tokenize(test_code)
    if lex_errors:
        print("词法错误：")
        for e in lex_errors:
            print(f"  ❌ {e}")
    
    ast = parse_tokens(tokens, [])
    errors, warnings = check_names(ast)
    
    if errors:
        print("名实校验错误：")
        for e in errors:
            print(f"  ❌ {e}")
    
    gen = CodeGenerator()
    python_code = gen.generate(ast)
    
    print("生成的 Python 代码：")
    print("-" * 60)
    print(python_code)
    print("-" * 60)
    
    if gen.warnings:
        print("\n警告：")
        for w in gen.warnings:
            print(f"  ⚠️ {w}")
    
    print(f"\n✅ 代码生成完成，共 {len(python_code.splitlines())} 行")
