#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""工作纪律 · 渲染器（真源 → 各 harness 产物）

真源（唯一手写）：docs/工作纪律_认知图条目_v1.1.json
适配矩阵        ：docs/discipline/harnesses.yaml
模板            ：docs/discipline/templates/*.tmpl

用法：
    python scripts/render_discipline.py --target dsh            # 干跑（摘要）
    python scripts/render_discipline.py --target dsh --print    # 干跑并打印全文
    python scripts/render_discipline.py --target dsh --write    # 落盘
    python scripts/render_discipline.py --all --write

纪律第 15 条：纯 Python 文件读写 + 显式 UTF-8，不经 Windows shell。
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys
from datetime import datetime

try:
    import yaml
except ImportError:  # pragma: no cover
    print("需要 PyYAML：python -m pip install pyyaml", file=sys.stderr)
    raise

REPO_DEFAULT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER_HEAD = "# >>> {marker} v{version} (auto-generated by render_discipline.py, do not edit) >>>"
MARKER_TAIL = "# <<< {marker} <<<"


def load_matrix(repo):
    with io.open(os.path.join(repo, "docs", "discipline", "harnesses.yaml"), encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_source(repo):
    mx = load_matrix(repo)
    path = os.path.join(repo, *mx["source"].split("/"))
    with io.open(path, encoding="utf-8") as f:
        return json.load(f)


def nodes_of(src):
    return list(src["subgraph"]["nodes"])


def source_path(repo):
    mx = load_matrix(repo)
    return os.path.join(repo, *mx["source"].split("/"))


def source_label(repo):
    return os.path.splitext(os.path.basename(source_path(repo)))[0]


def source_sha(repo):
    import hashlib
    with open(source_path(repo), "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


_NUM_PREFIX = re.compile(r"^\s*\d+\s*[.．、]\s*")


def _title(i, n):
    s = _NUM_PREFIX.sub("", str(n.get("semantic", n["id"])))
    return "%d. %s" % (i, s)


def expand(path, repo):
    if path.startswith("~"):
        return os.path.expanduser(path)
    return os.path.normpath(os.path.join(repo, path))


def _list_or(conds, default):
    items = [str(c) for c in (conds or []) if str(c).strip()]
    return "｜".join(items) if items else default


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


def render_routing_compact(nodes):
    out = []
    for i, n in enumerate(nodes, 1):
        cond = n.get("conditions", {}) or {}
        neg = n.get("negative", {}) or {}
        ex = n.get("execution", {}) or {}
        rs = n.get("response", {}) or {}
        out.append(_title(i, n))
        out.append("   触发：" + _list_or(cond.get("apply"), "（无前置条件，始终适用）"))
        out.append("   动作：" + str(ex.get("how", "")).strip())
        out.append("   不适用：" + _list_or(neg.get("reject"), "（无）"))
        out.append("   声明：" + str(rs.get("direct", "")).strip())
    return "\n".join(out)


def render_routing_full(nodes):
    out = []
    for i, n in enumerate(nodes, 1):
        cond = n.get("conditions", {}) or {}
        neg = n.get("negative", {}) or {}
        ex = n.get("execution", {}) or {}
        rs = n.get("response", {}) or {}
        out.append("### " + _title(i, n))
        out.append("")
        out.append("- **触发**：" + _list_or(cond.get("apply"), "（无前置条件，始终适用）"))
        out.append("- **动作**：" + str(ex.get("how", "")).strip())
        out.append("- **不适用**：" + _list_or(neg.get("reject"), "（无）"))
        out.append("- **声明**：" + str(rs.get("direct", "")).strip())
        out.append("")
    return "\n".join(out).rstrip()


def render_declaration_table(nodes):
    rows = ["| # | 声明（response.direct 原文） |", "|---|---|"]
    for i, n in enumerate(nodes, 1):
        rs = n.get("response", {}) or {}
        rows.append("| %d | %s |" % (i, _cell(rs.get("direct", ""))))
    return "\n".join(rows)


def render(target, src, repo, now=None):
    variant = target.get("variant", "compact")
    tname = "compact.txt.tmpl" if variant == "compact" else "full.md.tmpl"
    tpl_path = os.path.join(repo, "docs", "discipline", "templates", tname)
    with io.open(tpl_path, encoding="utf-8") as f:
        text = f.read()

    nodes = nodes_of(src)
    subs = {
        "%%VERSION%%": source_label(repo),
        "%%COUNT%%": str(len(nodes)),
        "%%SOURCE_SHA%%": source_sha(repo),
        "%%GENERATED_AT%%": now or datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "%%OVERVIEW%%": str(src.get("content", "")).strip(),
        "%%PREAMBLE%%": (target.get("preamble", "").rstrip() + "\n\n") if target.get("preamble") else "",
        "%%ROUTING_TABLE%%": render_routing_compact(nodes),
        "%%ROUTING_TABLE_FULL%%": render_routing_full(nodes),
        "%%DECLARATION_TABLE%%": render_declaration_table(nodes),
    }
    for k, v in subs.items():
        text = text.replace(k, v)

    if "{{" in text:
        raise SystemExit(
            "渲染结果含裸 '{{'，会与目标 harness 的严格变量插值冲突（DSH personaPrefix）。"
            "请检查真源字段是否含 '{{'。"
        )
    return text.rstrip() + "\n"


def _eol(text):
    return "\r\n" if "\r\n" in text else "\n"


def _find_entry_span(lines, entry_id):
    pat = re.compile(r"^-\s*id:\s*" + re.escape(entry_id) + r"\s*$")
    start = None
    for i, l in enumerate(lines):
        if pat.match(l.rstrip()):
            start = i
            break
    if start is None:
        return None
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if re.match(r"^-\s", lines[j]):
            end = j
            break
    return (start, end)


def _find_marker_span(lines, marker):
    head = tail = None
    for i, l in enumerate(lines):
        if ("# >>> " + marker) in l:
            head = i
        if ("# <<< " + marker) in l:
            tail = i
    if head is not None and tail is not None and tail > head:
        return (head, tail)
    return None


def _value_block(key, value, indent):
    block = [indent + key + ": |-"]
    for line in value.rstrip("\n").split("\n"):
        block.append(indent + "  " + line if line.strip() else "")
    return block


def read_config_key(target, repo):
    path = expand(target["path"], repo)
    if not os.path.isfile(path):
        return None, None
    with io.open(path, encoding="utf-8", newline="") as f:
        raw = f.read()
    eol = _eol(raw)
    lines = raw.split(eol)
    span = _find_marker_span(lines, target["marker"])
    if span is None:
        return None, eol
    body = lines[span[0] + 1: span[1]]
    kept = [l for l in body if not l.lstrip().startswith("#")]
    dedented = []
    for l in kept:
        dedented.append(l[6:] if l.startswith("      ") else l.lstrip())
    return "\n".join(dedented).rstrip() + "\n", eol


def write_config_key(target, repo, value, dry):
    path = expand(target["path"], repo)
    entry_id = target["entry_id"]
    key = target["key"]
    marker = target["marker"]
    version = target.get("version", 1)
    indent = "    "

    if os.path.isfile(path):
        with io.open(path, encoding="utf-8", newline="") as f:
            raw = f.read()
        eol = _eol(raw)
        lines = raw.split(eol)
    else:
        eol, lines = "\n", []

    head = MARKER_HEAD.format(marker=marker, version=version)
    tail = MARKER_TAIL.format(marker=marker)
    block = _value_block(key, value, indent)

    span = _find_marker_span(lines, marker)
    if span is not None:
        new_lines = lines[: span[0] + 1] + block + lines[span[1]:]
        action = "替换受管块"
    else:
        if _find_entry_span(lines, entry_id) is not None:
            raise SystemExit(
                "%s 已存在条目 id=%s 但没有受管标记 %s；拒绝自动改写（避免破坏手写内容）。"
                "请手工加标记或删该条目后重跑。" % (path, entry_id, marker)
            )
        while lines and lines[-1].strip() == "":
            lines.pop()
        new_lines = lines + ["", "- id: " + entry_id, "  config:", indent + head] + block + [indent + tail, ""]
        action = "新增条目"

    new_text = eol.join(new_lines)
    if not dry:
        d = os.path.dirname(path)
        if d:
            os.makedirs(d, exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="") as f:
            f.write(new_text)

    span2 = _find_marker_span(new_lines, marker)
    return {"action": action, "path": path, "entry": entry_id, "key": key,
            "lines": [span2[0] + 1, span2[1] + 1] if span2 else None}


def main(argv=None):
    ap = argparse.ArgumentParser(description="工作纪律渲染器（真源 → harness 产物）")
    ap.add_argument("--repo", default=REPO_DEFAULT)
    ap.add_argument("--target", action="append", default=[])
    ap.add_argument("--all", action="store_true", help="所有 enabled 目标")
    ap.add_argument("--write", action="store_true", help="落盘（默认干跑）")
    ap.add_argument("--print", dest="do_print", action="store_true", help="打印渲染全文")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    repo = os.path.abspath(args.repo)
    mx = load_matrix(repo)
    src = load_source(repo)
    targets = mx.get("targets", {})

    names = args.target or ([n for n, t in targets.items() if t.get("enabled")] if args.all else [])
    if not names:
        print("未指定目标：用 --target <name> 或 --all", file=sys.stderr)
        return 2

    report = []
    for name in names:
        t = targets.get(name)
        if t is None:
            print("未知目标：" + name, file=sys.stderr)
            return 2
        text = render(t, src, repo)
        rec = {"target": name, "variant": t.get("variant"), "transport": t.get("transport"),
               "bytes": len(text.encode("utf-8")), "chars": len(text)}
        if t.get("transport") == "file":
            path = expand(t["path"], repo)
            rec["path"] = path
            if args.write:
                d = os.path.dirname(path)
                if d:
                    os.makedirs(d, exist_ok=True)
                with io.open(path, "w", encoding="utf-8", newline="") as f:
                    f.write(text)
                rec["written"] = True
            else:
                rec["written"] = False
        else:
            info = write_config_key(t, repo, text, dry=not args.write)
            rec.update(info)
            rec["written"] = bool(args.write)
        report.append(rec)
        if args.do_print:
            print("===== " + name + " (" + str(t.get("variant")) + ") =====")
            print(text)

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        for r in report:
            extra = ""
            if r.get("entry"):
                extra = " entry=%s key=%s lines=%s" % (r.get("entry"), r.get("key"), r.get("lines"))
            print("[%s] variant=%s transport=%s chars=%d bytes=%d -> %s%s (%s) %s" % (
                r["target"], r["variant"], r["transport"], r["chars"], r["bytes"],
                r.get("path"), extra, ("已写入" if r.get("written") else "干跑"), r.get("action", "")))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
