#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""工作纪律 · 渲染器（真源 → 各 harness 产物）

真源（唯一手写）：docs/工作纪律_认知图条目_v1.1.json
适配矩阵        ：docs/discipline/harnesses.yaml
模板            ：docs/discipline/templates/*.tmpl

用法：
    python scripts/render_discipline.py --target dsh            # 干跑（摘要）
    python scripts/render_discipline.py --target dsh --print    # 干跑并打印全文
    python scripts/render_discipline.py --target dsh --write    # 落盘
    python scripts/render_discipline.py --all --write

纪律第 15 条：纯 Python 文件读写 + 显式 UTF-8，不经 Windows shell。
"""
from __future__ import annotations

import argparse
import io
import json
import os
import re
import sys
from datetime import datetime

try:
    import yaml
except ImportError:  # pragma: no cover
    print("需要 PyYAML：python -m pip install pyyaml", file=sys.stderr)
    raise

REPO_DEFAULT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
MARKER_HEAD = "# >>> {marker} v{version} (auto-generated by render_discipline.py, do not edit) >>>"
MARKER_TAIL = "# <<< {marker} <<<"


def load_matrix(repo):
    with io.open(os.path.join(repo, "docs", "discipline", "harnesses.yaml"), encoding="utf-8") as f:
        return yaml.safe_load(f)


def load_source(repo):
    mx = load_matrix(repo)
    path = os.path.join(repo, *mx["source"].split("/"))
    with io.open(path, encoding="utf-8") as f:
        return json.load(f)


def nodes_of(src):
    return list(src["subgraph"]["nodes"])


def source_path(repo):
    mx = load_matrix(repo)
    return os.path.join(repo, *mx["source"].split("/"))


def source_label(repo):
    return os.path.splitext(os.path.basename(source_path(repo)))[0]


def source_sha(repo):
    import hashlib
    with open(source_path(repo), "rb") as f:
        return hashlib.sha256(f.read()).hexdigest()[:16]


_NUM_PREFIX = re.compile(r"^\s*\d+\s*[.．、]\s*")


def _title(i, n):
    s = _NUM_PREFIX.sub("", str(n.get("semantic", n["id"])))
    return "%d. %s" % (i, s)


def expand(path, repo):
    if path.startswith("~"):
        return os.path.expanduser(path)
    return os.path.normpath(os.path.join(repo, path))


def _list_or(conds, default):
    items = [str(c) for c in (conds or []) if str(c).strip()]
    return "｜".join(items) if items else default


def _cell(text):
    return str(text).replace("|", "\\|").replace("\n", " ").strip()


# ------------------------------------------------- 注入面发现（Pi⑦⑤：祖先链发现 + 防重复）
# 依据：宿主 agent 的注入件**不是单点读取**——它从启动目录逐级上溯读同名件（AGENTS.md /
# CLAUDE.md / CODEBUDDY.md），故「产物落在哪」不等于「宿主只读到这一份」。三个可机械裁决的判据：
#   ① 同一物理文件被两个 target 写     → 后渲染者静默覆盖前者（写入冲突）；
#   ② 仓根出现会**遮蔽**本地私有件的槽位件 → 本地纪律注入在该宿主下失效（§5 明文纪律的机械化）；
#   ③ 同一条祖先链上并存同槽位件        → 宿主可能一并读到（重复注入）或按声明的择优顺序遮蔽，
#      属**宿主侧事实**：本仓无权裁决，但必须被**发现并报告**（而不是假定不存在）。
# 防重复（Pi⑦⑤ worktree）：去重落在**目录层**——走祖先链时按物理目录身份（realpath+normcase）
# 折叠别名拼写，使 worktree / junction / 大小写别名下同一份件只被查一次。
# 反面取舍已实证：按「git 仓身份 + 仓内相对路径」做键**会错**——worktree 与其主仓的 AGENTS.md
# 是同相对路径但**物理不同的两个文件**（各自 checkout 一份），折叠即把真实的重复注入源静默藏起。
# 故此类同仓不同物理文件只**标注**（wt_dups），不折叠。

def norm_path(path):
    """归一化路径键：realpath（解析符号链接 / junction）+ normcase（Windows 大小写不敏感）。"""
    return os.path.normcase(os.path.realpath(os.path.abspath(path)))


def _under(path, root):
    """path 是否落在 root 之内（含 root 自身）——按路径分量比较，防 dsh-memory-x 前缀误判。"""
    p, r = norm_path(path), norm_path(root)
    return p == r or p.startswith(r.rstrip(os.sep) + os.sep)


def injection_conf(matrix):
    """注入面声明段（矩阵 injection:）；未声明则返回空 dict（本能力整体静默降级）。"""
    return matrix.get("injection") or {}


def slot_files(matrix, slot):
    """该注入槽位的竞争文件名（有序 = 声明的宿主择优优先级，首项优先）。"""
    slots = injection_conf(matrix).get("slots") or {}
    return [str(x) for x in (slots.get(slot) or [])]


def _walk_ancestors(path, stop=None):
    """走祖先目录链，返回 (去重后的目录链, 被折叠的别名拼写)。

    去重键 = norm_path（realpath + normcase），即**物理目录身份**：
      · 同一物理目录经 junction / symlink / 大小写等别名在链上出现两次 → 只查一次，
        第二次记为 alias（`{"dir","alias_of"}`）—— 这就是「防重复」在目录层的落点：
        宿主逐级上溯时，同一份件只会被本工具发现一次，不会误报成两份。
      · 退出条件二选一：命中 stop（stop 本身**含**进链）或到达盘根。dirname 严格变短，
        故 junction 自环也不会死循环。
    """
    out, seen, alias = [], {}, []
    cur = os.path.dirname(os.path.abspath(path))
    stop_key = norm_path(stop) if stop else None
    while True:
        key = norm_path(cur)
        if key in seen:
            alias.append({"dir": cur, "alias_of": seen[key]})
        else:
            seen[key] = cur
            out.append(cur)
        if stop_key and key == stop_key:
            break
        parent = os.path.dirname(cur)
        if parent == cur:
            break
        cur = parent
    return out, alias


def ancestor_dirs(path, stop=None):
    """祖先目录链（最近 → 最远）：起点 = path 所在目录，含其自身。

    stop 给定时把 stop **含**进链后停止（仓内检查用 stop=仓根）；缺省一路到盘根
    （宿主侧事实要能被看见，故默认不收窄）。
    """
    return _walk_ancestors(path, stop)[0]


def ancestor_alias_hits(path, stop=None):
    """链上被折叠掉的别名目录拼写（同一物理目录出现两次时的后来者）。"""
    return _walk_ancestors(path, stop)[1]


_GIT_ID_CACHE = {}


def _git(args, cwd):
    import subprocess
    try:
        r = subprocess.run(["git"] + list(args), cwd=cwd, capture_output=True,
                           text=True, encoding="utf-8", errors="replace", timeout=5)
    except (OSError, ValueError, subprocess.SubprocessError):
        return None
    return r.stdout.strip() if r.returncode == 0 else None


def git_identity(path):
    """(common_dir, 仓内相对路径) —— worktree 与主仓共享 common_dir，故「同一逻辑件」
    （同仓同相对路径）在 worktree 副本里键相同 → 用于**标注**「同仓另一 worktree 亦有一份」。

    非 git 环境或 git 不可用 → (None, None)：调用方退化为 realpath 去重（宁少报不误报）。
    结果按目录缓存（一次校验内多次调用同一目录只起一个 git 进程）。
    """
    d = os.path.dirname(os.path.abspath(path))
    if d in _GIT_ID_CACHE:
        base = _GIT_ID_CACHE[d]
    else:
        probe = d
        base = (None, None)
        while True:
            if os.path.exists(os.path.join(probe, ".git")):
                top = _git(["rev-parse", "--show-toplevel"], probe)
                common = (_git(["rev-parse", "--path-format=absolute",
                                "--git-common-dir"], probe)
                          or _git(["rev-parse", "--git-common-dir"], probe))
                if top and common:
                    if not os.path.isabs(common):
                        common = os.path.join(probe, common)
                    base = (norm_path(common), os.path.abspath(top))
                break
            parent = os.path.dirname(probe)
            if parent == probe:
                break
            probe = parent
        _GIT_ID_CACHE[d] = base
    common, top = base
    if not common:
        return None, None
    try:
        rel = os.path.relpath(os.path.abspath(path), top).replace("\\", "/")
    except ValueError:          # Windows 跨盘符
        return None, None
    return common, rel


def artifact_sha(text):
    """产物内嵌的真源指纹（『前16位：xxxxxxxxxxxxxxxx』）；无指纹（手工件/未渲染）→ None。"""
    m = re.search(r"前16位[）：:]*\s*([0-9a-f]{16})", text or "")
    return m.group(1) if m else None


def discover_injection_chain(target, repo, matrix, scope=None):
    """祖先链发现：列出这条链上与 target **同槽位**的注入件（事实清单，不做裁决）。

    返回：
      slot   槽位名（无槽位 / 非文件目标 → None，调用方据此跳过）
      files  该槽位的竞争文件名（有序 = 声明优先级）
      hits   [{"path","dir","tier","rank","self_rank","sha","same_name","repo_id"}]
             tier=repo（仓内）/ outside（仓外，宿主侧事实）；rank < self_rank ⇒ 声明顺序下自身被遮蔽
      dedup  [{"dir","alias_of"}]   同一**物理目录**经别名在链上出现两次 → 折叠（防重复）
      wt_dups [{"path","alias_of"}] 同仓（git common_dir + 相对路径相同）但**物理不同**的份
    """
    slot = target.get("slot")
    if target.get("transport") != "file" or not slot:
        return {"slot": None, "files": [], "hits": [], "dedup": [], "wt_dups": []}
    files = slot_files(matrix, slot)
    if not files:
        return {"slot": None, "files": [], "hits": [], "dedup": [], "wt_dups": []}

    scope = scope or injection_conf(matrix).get("chain_scope") or "filesystem"
    stop = os.path.abspath(repo) if scope == "repo" else None
    tpath = expand(target["path"], repo)
    self_key, self_name = norm_path(tpath), os.path.basename(tpath)
    self_rank = files.index(self_name) if self_name in files else len(files)

    dirs, dedup = _walk_ancestors(tpath, stop=stop)
    hits = []
    for d in dirs:
        for fn in files:
            p = os.path.join(d, fn)
            if not os.path.isfile(p):
                continue
            if norm_path(p) == self_key:
                continue                      # 自身
            try:
                with io.open(p, encoding="utf-8", errors="replace") as f:
                    sha = artifact_sha(f.read(65536))
            except OSError:
                sha = None
            common, rel = git_identity(p)
            hits.append({"path": p, "dir": d,
                         "tier": "repo" if _under(d, repo) else "outside",
                         "rank": files.index(fn), "self_rank": self_rank,
                         "sha": sha, "same_name": fn == self_name,
                         "repo_id": (common, rel) if common else None})

    # worktree 重复发现（Pi⑦⑤）：同仓同相对路径的另一份 = **物理不同的另一个文件**。
    # 关键取舍：**不折叠**——折叠会把「两份都可能被宿主读到的注入源」静默藏起来，
    # 与去重的初衷（防止把同一份误报两次）相反。故只标注，由报告面交人裁决。
    wt_dups, by_repo = [], {}
    for h in hits:
        if not h["repo_id"]:
            continue
        seen_p = by_repo.get(h["repo_id"])
        if seen_p and norm_path(seen_p) != norm_path(h["path"]):
            wt_dups.append({"path": h["path"], "alias_of": seen_p})
        else:
            by_repo.setdefault(h["repo_id"], h["path"])
    return {"slot": slot, "files": files, "hits": hits, "dedup": dedup,
            "wt_dups": wt_dups}


def render_routing_compact(nodes):
    out = []
    for i, n in enumerate(nodes, 1):
        cond = n.get("conditions", {}) or {}
        neg = n.get("negative", {}) or {}
        ex = n.get("execution", {}) or {}
        rs = n.get("response", {}) or {}
        out.append(_title(i, n))
        out.append("   触发：" + _list_or(cond.get("apply"), "（无前置条件，始终适用）"))
        out.append("   动作：" + str(ex.get("how", "")).strip())
        out.append("   不适用：" + _list_or(neg.get("reject"), "（无）"))
        out.append("   声明：" + str(rs.get("direct", "")).strip())
    return "\n".join(out)


def render_routing_full(nodes):
    out = []
    for i, n in enumerate(nodes, 1):
        cond = n.get("conditions", {}) or {}
        neg = n.get("negative", {}) or {}
        ex = n.get("execution", {}) or {}
        rs = n.get("response", {}) or {}
        out.append("### " + _title(i, n))
        out.append("")
        out.append("- **触发**：" + _list_or(cond.get("apply"), "（无前置条件，始终适用）"))
        out.append("- **动作**：" + str(ex.get("how", "")).strip())
        out.append("- **不适用**：" + _list_or(neg.get("reject"), "（无）"))
        out.append("- **声明**：" + str(rs.get("direct", "")).strip())
        out.append("")
    return "\n".join(out).rstrip()


def render_declaration_table(nodes):
    rows = ["| # | 声明（response.direct 原文） |", "|---|---|"]
    for i, n in enumerate(nodes, 1):
        rs = n.get("response", {}) or {}
        rows.append("| %d | %s |" % (i, _cell(rs.get("direct", ""))))
    return "\n".join(rows)


_TEMPLATES = {
    "compact": "compact.txt.tmpl",
    "full": "full.md.tmpl",
    "skill": "skill.md.tmpl",  # SKILL.md 形态（YAML frontmatter + 纪律正文），供插件 skills/ 目录
}


def render(target, src, repo, now=None):
    variant = target.get("variant", "compact")
    tname = _TEMPLATES.get(variant)
    if tname is None:
        raise SystemExit("未知 variant：%r（支持 compact / full / skill）" % (variant,))
    tpl_path = os.path.join(repo, "docs", "discipline", "templates", tname)
    with io.open(tpl_path, encoding="utf-8") as f:
        text = f.read()

    nodes = nodes_of(src)
    subs = {
        "%%VERSION%%": source_label(repo),
        "%%COUNT%%": str(len(nodes)),
        "%%SOURCE_SHA%%": source_sha(repo),
        "%%GENERATED_AT%%": now or datetime.now().strftime("%Y-%m-%d %H:%M:%S"),
        "%%OVERVIEW%%": str(src.get("content", "")).strip(),
        "%%PREAMBLE%%": (target.get("preamble", "").rstrip() + "\n\n") if target.get("preamble") else "",
        "%%ROUTING_TABLE%%": render_routing_compact(nodes),
        "%%ROUTING_TABLE_FULL%%": render_routing_full(nodes),
        "%%DECLARATION_TABLE%%": render_declaration_table(nodes),
    }
    for k, v in subs.items():
        text = text.replace(k, v)

    if "{{" in text:
        raise SystemExit(
            "渲染结果含裸 '{{'，会与目标 harness 的严格变量插值冲突（DSH personaPrefix）。"
            "请检查真源字段是否含 '{{'。"
        )
    return text.rstrip() + "\n"


def _eol(text):
    return "\r\n" if "\r\n" in text else "\n"


def _find_entry_span(lines, entry_id):
    pat = re.compile(r"^-\s*id:\s*" + re.escape(entry_id) + r"\s*$")
    start = None
    for i, l in enumerate(lines):
        if pat.match(l.rstrip()):
            start = i
            break
    if start is None:
        return None
    end = len(lines)
    for j in range(start + 1, len(lines)):
        if re.match(r"^-\s", lines[j]):
            end = j
            break
    return (start, end)


def _find_marker_span(lines, marker):
    head = tail = None
    for i, l in enumerate(lines):
        if ("# >>> " + marker) in l:
            head = i
        if ("# <<< " + marker) in l:
            tail = i
    if head is not None and tail is not None and tail > head:
        return (head, tail)
    return None


def _value_block(key, value, indent):
    block = [indent + key + ": |-"]
    for line in value.rstrip("\n").split("\n"):
        block.append(indent + "  " + line if line.strip() else "")
    return block


def read_config_key(target, repo):
    path = expand(target["path"], repo)
    if not os.path.isfile(path):
        return None, None
    with io.open(path, encoding="utf-8", newline="") as f:
        raw = f.read()
    eol = _eol(raw)
    lines = raw.split(eol)
    span = _find_marker_span(lines, target["marker"])
    if span is None:
        return None, eol
    body = lines[span[0] + 1: span[1]]
    kept = [l for l in body if not l.lstrip().startswith("#")]
    dedented = []
    for l in kept:
        dedented.append(l[6:] if l.startswith("      ") else l.lstrip())
    return "\n".join(dedented).rstrip() + "\n", eol


def write_config_key(target, repo, value, dry):
    path = expand(target["path"], repo)
    entry_id = target["entry_id"]
    key = target["key"]
    marker = target["marker"]
    version = target.get("version", 1)
    indent = "    "

    if os.path.isfile(path):
        with io.open(path, encoding="utf-8", newline="") as f:
            raw = f.read()
        eol = _eol(raw)
        lines = raw.split(eol)
    else:
        eol, lines = "\n", []

    head = MARKER_HEAD.format(marker=marker, version=version)
    tail = MARKER_TAIL.format(marker=marker)
    block = _value_block(key, value, indent)

    span = _find_marker_span(lines, marker)
    if span is not None:
        new_lines = lines[: span[0] + 1] + block + lines[span[1]:]
        action = "替换受管块"
    else:
        if _find_entry_span(lines, entry_id) is not None:
            raise SystemExit(
                "%s 已存在条目 id=%s 但没有受管标记 %s；拒绝自动改写（避免破坏手写内容）。"
                "请手工加标记或删该条目后重跑。" % (path, entry_id, marker)
            )
        while lines and lines[-1].strip() == "":
            lines.pop()
        new_lines = lines + ["", "- id: " + entry_id, "  config:", indent + head] + block + [indent + tail, ""]
        action = "新增条目"

    new_text = eol.join(new_lines)
    if not dry:
        d = os.path.dirname(path)
        if d:
            os.makedirs(d, exist_ok=True)
        with io.open(path, "w", encoding="utf-8", newline="") as f:
            f.write(new_text)

    span2 = _find_marker_span(new_lines, marker)
    return {"action": action, "path": path, "entry": entry_id, "key": key,
            "lines": [span2[0] + 1, span2[1] + 1] if span2 else None}


def main(argv=None):
    ap = argparse.ArgumentParser(description="工作纪律渲染器（真源 → harness 产物）")
    ap.add_argument("--repo", default=REPO_DEFAULT)
    ap.add_argument("--target", action="append", default=[])
    ap.add_argument("--all", action="store_true", help="所有 enabled 目标")
    ap.add_argument("--write", action="store_true", help="落盘（默认干跑）")
    ap.add_argument("--print", dest="do_print", action="store_true", help="打印渲染全文")
    ap.add_argument("--cg-root", default=None,
                    help="认知图 root：顺带同步 structural/ 投影节点（缺省读环境变量 MDCG_ROOT；都无则跳过）")
    ap.add_argument("--json", action="store_true")
    args = ap.parse_args(argv)

    repo = os.path.abspath(args.repo)
    mx = load_matrix(repo)
    src = load_source(repo)
    targets = mx.get("targets", {})

    # render: false 的 target（本地私有手工件）不参与 --all 渲染：渲染会覆盖其本地增强段。
    names = args.target or ([n for n, t in targets.items()
                             if t.get("enabled") and t.get("render", True)] if args.all else [])
    if not names:
        print("未指定目标：用 --target <name> 或 --all", file=sys.stderr)
        return 2

    report = []
    for name in names:
        t = targets.get(name)
        if t is None:
            print("未知目标：" + name, file=sys.stderr)
            return 2
        text = render(t, src, repo)
        rec = {"target": name, "variant": t.get("variant"), "transport": t.get("transport"),
               "bytes": len(text.encode("utf-8")), "chars": len(text)}
        if t.get("transport") == "file":
            path = expand(t["path"], repo)
            rec["path"] = path
            if t.get("render") is False:
                rec["render"] = False
            if args.write and t.get("render") is False:
                raise SystemExit(
                    "目标 %s 声明 render: false（本地私有手工件，渲染会覆盖其本地增强段）：%s\n"
                    "拒绝写盘。如需改动请直接编辑该文件，或先显式移除矩阵里的 render: false。"
                    % (name, path)
                )
            if args.write:
                d = os.path.dirname(path)
                if d:
                    os.makedirs(d, exist_ok=True)
                with io.open(path, "w", encoding="utf-8", newline="") as f:
                    f.write(text)
                rec["written"] = True
            else:
                rec["written"] = False
        else:
            info = write_config_key(t, repo, text, dry=not args.write)
            rec.update(info)
            rec["written"] = bool(args.write)
        report.append(rec)
        if args.do_print:
            print("===== " + name + " (" + str(t.get("variant")) + ") =====")
            print(text)

    if args.json:
        print(json.dumps(report, ensure_ascii=False, indent=2))
    else:
        for r in report:
            extra = ""
            if r.get("entry"):
                extra = " entry=%s key=%s lines=%s" % (r.get("entry"), r.get("key"), r.get("lines"))
            print("[%s] variant=%s transport=%s chars=%d bytes=%d -> %s%s (%s) %s" % (
                r["target"], r["variant"], r["transport"], r["chars"], r["bytes"],
                r.get("path"), extra, ("已写入" if r.get("written") else "干跑"), r.get("action", "")))

    # 认知图投影节点同步（2026-09-16）：纪律在本机灵枢认知图 structural/ 下还有一份
    # 投影（tags 含 discipline:N），是 route 命中纪律的检索面。它此前是手工快照、不在
    # 渲染矩阵内 → 改真源后必然陈化（实例：第16条新增「读回确认」后投影仍停留旧
    # source_sha/旧正文；第17条无投影节点）。此处并入渲染链路一并刷新。
    # root 未提供（--cg-root / MDCG_ROOT）则跳过——外部 clone 不产生任何依赖。
    import discipline_nodes as DN
    cg_rep = DN.sync_cg_nodes(repo, DN.resolve_root(args.cg_root), write=args.write)
    if not args.json:
        if cg_rep.get("skipped"):
            print("[SKIP] " + cg_rep["reason"])
        else:
            for r in cg_rep["created"]:
                print("[认知图投影] 新建 第%d条 -> %s" % (r["no"], r["path"]))
            for r in cg_rep["changed"]:
                print("[认知图投影] 同步 第%d条 %s -> %s" % (r["no"], r["id"], r["path"]))
            if not cg_rep["created"] and not cg_rep["changed"]:
                print("[认知图投影] 已一致（真源指纹 %s）" % cg_rep["source_sha"])
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
